# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
    -   id: isort
        name: isort
        args: ["--profile", "black"]
        entry: isort
        language: system
        types: [python]
